baseURL: https://gabrielcalandriwebsite.netlify.app/
languageCode: en-us
title: Portfolio for Gabriel Calandri
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: Hi, my name is Gabriel Calandri. I am currently a MAM Student at LBS and am pleased to present you some pieces of my life and my work done so far.
    title: Gabriel Calandri's Portfolio
  blog: {}
  contact:
    address:
      - city: London NW1 4SA
        country: United Kingdom
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: gcalandri.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (734) 033-3625 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Calandri Holding Inc.
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
      # - icon: fa-facebook
      #   label: Facebook
      #   url: https://www.facebook.com
      # - icon: fa-instagram
      #   label: Instagram
      #   url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/GabrielCalandri22
      - icon: fa-linkedin
        label: LinkedIn
        url: https://linkedin.com/in/gabrielcalandri
  image: universe.jpg
  name: Gabriel Calandri
  navigation:
    button1:
      - name: My Projects
        url: projects
    # button2:
    #   - name: Get Started
    #     url: '#'
    links:
      - name: Home
        url: '#'
      # - name: Blogs
      #   url: blogs
      # - name: Generic Blog
      #   url: blogs/ipsum
      # - name: Elements
      #   url: elements.html
    menu: Menu
    subtitle: By Gabriel Calandri
    title: Project Portfolio
  tiles:
    enable: yes
    showcase:
      - image: kiting.jpg
        subtitle: Deep Dive Into Who I Am
        title: About Me
        url: about_me/me
      - image: growth.jpg
        subtitle: 
        title: My CV
        url: about_me/cv_gabriel_calandri.pdf
      - image: success_on_top.jpg
        subtitle:
        title: Extra-Curricular Certification
        url: about_me/BGS.pdf
      - image: stonks.jpg
        subtitle: 
        title: Online Course Certification
        url: about_me/BMC.jpg
      # - image: 4renewables.JPEG
      #   subtitle: Study of the Share of Rewewable Energy Production around the Globe
      #   title: Renewable Energy Production Across the World
      #   url: Projects/renewables
      # - image: santander.JPEG
      #   subtitle: Study of the excess in rentals of TFL sharing bikes during the period 2017-2022
      #   title: Excess Rentals in TFL Bike Sharing
      #   url: Projects/bike_sharing
      # - image: pic06.jpg
      #   subtitle: Feugiat Amet Tempus
      #   title: Etiam
      #   url: blogs/ipsum
  two:
    buttonText: My Projects
    enable: yes
    subtitle: "A glimpse at some projects I worked on during my time at LBS."
    title: My LBS Projects
    url: projects
